version: '3.8'

services:
  backend:
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
      - "8501-8599:8501-8599"



  client:
    build:
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"

